switch to "pkg-config"
I get a build error saying:

	ERROR: /usr/bin/libpng16-config should not be used, use an alternative such as pkg-config

Therefore switch to the more common and more generic "pkg-config" instead of
using a libpng-specific tool for flags and libraries.

Signed-off-by: Trevor Woerner <twoerner@gmail.com>