change library linking order
Since -lraspidmxPng requires the png library (libpng), re-arrange the order of
linking so that it succeeds. Otherwise I get errors like the following:

	undefined reference to `png_create_write_struct'

...as well as undefined references to various other libpng objects.

Signed-off-by: Trevor Woerner <twoerner@gmail.com>